// <auto-generated />
using ButtonStatistics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ButtonStatistics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208181206_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ButtonStatistics.Models.Day", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Index = 0,
                            Count = 0
                        },
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        },
                        new
                        {
                            Index = 7,
                            Count = 0
                        },
                        new
                        {
                            Index = 8,
                            Count = 0
                        },
                        new
                        {
                            Index = 9,
                            Count = 0
                        },
                        new
                        {
                            Index = 10,
                            Count = 0
                        },
                        new
                        {
                            Index = 11,
                            Count = 0
                        },
                        new
                        {
                            Index = 12,
                            Count = 0
                        },
                        new
                        {
                            Index = 13,
                            Count = 0
                        },
                        new
                        {
                            Index = 14,
                            Count = 0
                        },
                        new
                        {
                            Index = 15,
                            Count = 0
                        },
                        new
                        {
                            Index = 16,
                            Count = 0
                        },
                        new
                        {
                            Index = 17,
                            Count = 0
                        },
                        new
                        {
                            Index = 18,
                            Count = 0
                        },
                        new
                        {
                            Index = 19,
                            Count = 0
                        },
                        new
                        {
                            Index = 20,
                            Count = 0
                        },
                        new
                        {
                            Index = 21,
                            Count = 0
                        },
                        new
                        {
                            Index = 22,
                            Count = 0
                        },
                        new
                        {
                            Index = 23,
                            Count = 0
                        },
                        new
                        {
                            Index = 24,
                            Count = 0
                        },
                        new
                        {
                            Index = 25,
                            Count = 0
                        },
                        new
                        {
                            Index = 26,
                            Count = 0
                        },
                        new
                        {
                            Index = 27,
                            Count = 0
                        },
                        new
                        {
                            Index = 28,
                            Count = 0
                        },
                        new
                        {
                            Index = 29,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.Hour", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Hours");

                    b.HasData(
                        new
                        {
                            Index = 0,
                            Count = 0
                        },
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        },
                        new
                        {
                            Index = 7,
                            Count = 0
                        },
                        new
                        {
                            Index = 8,
                            Count = 0
                        },
                        new
                        {
                            Index = 9,
                            Count = 0
                        },
                        new
                        {
                            Index = 10,
                            Count = 0
                        },
                        new
                        {
                            Index = 11,
                            Count = 0
                        },
                        new
                        {
                            Index = 12,
                            Count = 0
                        },
                        new
                        {
                            Index = 13,
                            Count = 0
                        },
                        new
                        {
                            Index = 14,
                            Count = 0
                        },
                        new
                        {
                            Index = 15,
                            Count = 0
                        },
                        new
                        {
                            Index = 16,
                            Count = 0
                        },
                        new
                        {
                            Index = 17,
                            Count = 0
                        },
                        new
                        {
                            Index = 18,
                            Count = 0
                        },
                        new
                        {
                            Index = 19,
                            Count = 0
                        },
                        new
                        {
                            Index = 20,
                            Count = 0
                        },
                        new
                        {
                            Index = 21,
                            Count = 0
                        },
                        new
                        {
                            Index = 22,
                            Count = 0
                        },
                        new
                        {
                            Index = 23,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.Minute", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Minutes");

                    b.HasData(
                        new
                        {
                            Index = 0,
                            Count = 0
                        },
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        },
                        new
                        {
                            Index = 7,
                            Count = 0
                        },
                        new
                        {
                            Index = 8,
                            Count = 0
                        },
                        new
                        {
                            Index = 9,
                            Count = 0
                        },
                        new
                        {
                            Index = 10,
                            Count = 0
                        },
                        new
                        {
                            Index = 11,
                            Count = 0
                        },
                        new
                        {
                            Index = 12,
                            Count = 0
                        },
                        new
                        {
                            Index = 13,
                            Count = 0
                        },
                        new
                        {
                            Index = 14,
                            Count = 0
                        },
                        new
                        {
                            Index = 15,
                            Count = 0
                        },
                        new
                        {
                            Index = 16,
                            Count = 0
                        },
                        new
                        {
                            Index = 17,
                            Count = 0
                        },
                        new
                        {
                            Index = 18,
                            Count = 0
                        },
                        new
                        {
                            Index = 19,
                            Count = 0
                        },
                        new
                        {
                            Index = 20,
                            Count = 0
                        },
                        new
                        {
                            Index = 21,
                            Count = 0
                        },
                        new
                        {
                            Index = 22,
                            Count = 0
                        },
                        new
                        {
                            Index = 23,
                            Count = 0
                        },
                        new
                        {
                            Index = 24,
                            Count = 0
                        },
                        new
                        {
                            Index = 25,
                            Count = 0
                        },
                        new
                        {
                            Index = 26,
                            Count = 0
                        },
                        new
                        {
                            Index = 27,
                            Count = 0
                        },
                        new
                        {
                            Index = 28,
                            Count = 0
                        },
                        new
                        {
                            Index = 29,
                            Count = 0
                        },
                        new
                        {
                            Index = 30,
                            Count = 0
                        },
                        new
                        {
                            Index = 31,
                            Count = 0
                        },
                        new
                        {
                            Index = 32,
                            Count = 0
                        },
                        new
                        {
                            Index = 33,
                            Count = 0
                        },
                        new
                        {
                            Index = 34,
                            Count = 0
                        },
                        new
                        {
                            Index = 35,
                            Count = 0
                        },
                        new
                        {
                            Index = 36,
                            Count = 0
                        },
                        new
                        {
                            Index = 37,
                            Count = 0
                        },
                        new
                        {
                            Index = 38,
                            Count = 0
                        },
                        new
                        {
                            Index = 39,
                            Count = 0
                        },
                        new
                        {
                            Index = 40,
                            Count = 0
                        },
                        new
                        {
                            Index = 41,
                            Count = 0
                        },
                        new
                        {
                            Index = 42,
                            Count = 0
                        },
                        new
                        {
                            Index = 43,
                            Count = 0
                        },
                        new
                        {
                            Index = 44,
                            Count = 0
                        },
                        new
                        {
                            Index = 45,
                            Count = 0
                        },
                        new
                        {
                            Index = 46,
                            Count = 0
                        },
                        new
                        {
                            Index = 47,
                            Count = 0
                        },
                        new
                        {
                            Index = 48,
                            Count = 0
                        },
                        new
                        {
                            Index = 49,
                            Count = 0
                        },
                        new
                        {
                            Index = 50,
                            Count = 0
                        },
                        new
                        {
                            Index = 51,
                            Count = 0
                        },
                        new
                        {
                            Index = 52,
                            Count = 0
                        },
                        new
                        {
                            Index = 53,
                            Count = 0
                        },
                        new
                        {
                            Index = 54,
                            Count = 0
                        },
                        new
                        {
                            Index = 55,
                            Count = 0
                        },
                        new
                        {
                            Index = 56,
                            Count = 0
                        },
                        new
                        {
                            Index = 57,
                            Count = 0
                        },
                        new
                        {
                            Index = 58,
                            Count = 0
                        },
                        new
                        {
                            Index = 59,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.Second", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Seconds");

                    b.HasData(
                        new
                        {
                            Index = 0,
                            Count = 0
                        },
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        },
                        new
                        {
                            Index = 7,
                            Count = 0
                        },
                        new
                        {
                            Index = 8,
                            Count = 0
                        },
                        new
                        {
                            Index = 9,
                            Count = 0
                        },
                        new
                        {
                            Index = 10,
                            Count = 0
                        },
                        new
                        {
                            Index = 11,
                            Count = 0
                        },
                        new
                        {
                            Index = 12,
                            Count = 0
                        },
                        new
                        {
                            Index = 13,
                            Count = 0
                        },
                        new
                        {
                            Index = 14,
                            Count = 0
                        },
                        new
                        {
                            Index = 15,
                            Count = 0
                        },
                        new
                        {
                            Index = 16,
                            Count = 0
                        },
                        new
                        {
                            Index = 17,
                            Count = 0
                        },
                        new
                        {
                            Index = 18,
                            Count = 0
                        },
                        new
                        {
                            Index = 19,
                            Count = 0
                        },
                        new
                        {
                            Index = 20,
                            Count = 0
                        },
                        new
                        {
                            Index = 21,
                            Count = 0
                        },
                        new
                        {
                            Index = 22,
                            Count = 0
                        },
                        new
                        {
                            Index = 23,
                            Count = 0
                        },
                        new
                        {
                            Index = 24,
                            Count = 0
                        },
                        new
                        {
                            Index = 25,
                            Count = 0
                        },
                        new
                        {
                            Index = 26,
                            Count = 0
                        },
                        new
                        {
                            Index = 27,
                            Count = 0
                        },
                        new
                        {
                            Index = 28,
                            Count = 0
                        },
                        new
                        {
                            Index = 29,
                            Count = 0
                        },
                        new
                        {
                            Index = 30,
                            Count = 0
                        },
                        new
                        {
                            Index = 31,
                            Count = 0
                        },
                        new
                        {
                            Index = 32,
                            Count = 0
                        },
                        new
                        {
                            Index = 33,
                            Count = 0
                        },
                        new
                        {
                            Index = 34,
                            Count = 0
                        },
                        new
                        {
                            Index = 35,
                            Count = 0
                        },
                        new
                        {
                            Index = 36,
                            Count = 0
                        },
                        new
                        {
                            Index = 37,
                            Count = 0
                        },
                        new
                        {
                            Index = 38,
                            Count = 0
                        },
                        new
                        {
                            Index = 39,
                            Count = 0
                        },
                        new
                        {
                            Index = 40,
                            Count = 0
                        },
                        new
                        {
                            Index = 41,
                            Count = 0
                        },
                        new
                        {
                            Index = 42,
                            Count = 0
                        },
                        new
                        {
                            Index = 43,
                            Count = 0
                        },
                        new
                        {
                            Index = 44,
                            Count = 0
                        },
                        new
                        {
                            Index = 45,
                            Count = 0
                        },
                        new
                        {
                            Index = 46,
                            Count = 0
                        },
                        new
                        {
                            Index = 47,
                            Count = 0
                        },
                        new
                        {
                            Index = 48,
                            Count = 0
                        },
                        new
                        {
                            Index = 49,
                            Count = 0
                        },
                        new
                        {
                            Index = 50,
                            Count = 0
                        },
                        new
                        {
                            Index = 51,
                            Count = 0
                        },
                        new
                        {
                            Index = 52,
                            Count = 0
                        },
                        new
                        {
                            Index = 53,
                            Count = 0
                        },
                        new
                        {
                            Index = 54,
                            Count = 0
                        },
                        new
                        {
                            Index = 55,
                            Count = 0
                        },
                        new
                        {
                            Index = 56,
                            Count = 0
                        },
                        new
                        {
                            Index = 57,
                            Count = 0
                        },
                        new
                        {
                            Index = 58,
                            Count = 0
                        },
                        new
                        {
                            Index = 59,
                            Count = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
