// <auto-generated />
using System;
using ButtonStatistics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ButtonStatistics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124104600_DonationRequestUpdate")]
    partial class DonationRequestUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ButtonStatistics.Models.CountryClick", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("CountryCode");

                    b.ToTable("CountryClicks");

                    b.HasData(
                        new
                        {
                            CountryCode = "ZZ",
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.Day", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        },
                        new
                        {
                            Index = 7,
                            Count = 0
                        },
                        new
                        {
                            Index = 8,
                            Count = 0
                        },
                        new
                        {
                            Index = 9,
                            Count = 0
                        },
                        new
                        {
                            Index = 10,
                            Count = 0
                        },
                        new
                        {
                            Index = 11,
                            Count = 0
                        },
                        new
                        {
                            Index = 12,
                            Count = 0
                        },
                        new
                        {
                            Index = 13,
                            Count = 0
                        },
                        new
                        {
                            Index = 14,
                            Count = 0
                        },
                        new
                        {
                            Index = 15,
                            Count = 0
                        },
                        new
                        {
                            Index = 16,
                            Count = 0
                        },
                        new
                        {
                            Index = 17,
                            Count = 0
                        },
                        new
                        {
                            Index = 18,
                            Count = 0
                        },
                        new
                        {
                            Index = 19,
                            Count = 0
                        },
                        new
                        {
                            Index = 20,
                            Count = 0
                        },
                        new
                        {
                            Index = 21,
                            Count = 0
                        },
                        new
                        {
                            Index = 22,
                            Count = 0
                        },
                        new
                        {
                            Index = 23,
                            Count = 0
                        },
                        new
                        {
                            Index = 24,
                            Count = 0
                        },
                        new
                        {
                            Index = 25,
                            Count = 0
                        },
                        new
                        {
                            Index = 26,
                            Count = 0
                        },
                        new
                        {
                            Index = 27,
                            Count = 0
                        },
                        new
                        {
                            Index = 28,
                            Count = 0
                        },
                        new
                        {
                            Index = 29,
                            Count = 0
                        },
                        new
                        {
                            Index = 30,
                            Count = 0
                        },
                        new
                        {
                            Index = 31,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.DonationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("Milestone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DonationRequests");
                });

            modelBuilder.Entity("ButtonStatistics.Models.Hour", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Hours");

                    b.HasData(
                        new
                        {
                            Index = 0,
                            Count = 0
                        },
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        },
                        new
                        {
                            Index = 7,
                            Count = 0
                        },
                        new
                        {
                            Index = 8,
                            Count = 0
                        },
                        new
                        {
                            Index = 9,
                            Count = 0
                        },
                        new
                        {
                            Index = 10,
                            Count = 0
                        },
                        new
                        {
                            Index = 11,
                            Count = 0
                        },
                        new
                        {
                            Index = 12,
                            Count = 0
                        },
                        new
                        {
                            Index = 13,
                            Count = 0
                        },
                        new
                        {
                            Index = 14,
                            Count = 0
                        },
                        new
                        {
                            Index = 15,
                            Count = 0
                        },
                        new
                        {
                            Index = 16,
                            Count = 0
                        },
                        new
                        {
                            Index = 17,
                            Count = 0
                        },
                        new
                        {
                            Index = 18,
                            Count = 0
                        },
                        new
                        {
                            Index = 19,
                            Count = 0
                        },
                        new
                        {
                            Index = 20,
                            Count = 0
                        },
                        new
                        {
                            Index = 21,
                            Count = 0
                        },
                        new
                        {
                            Index = 22,
                            Count = 0
                        },
                        new
                        {
                            Index = 23,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.LocalHour", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("LocalHours");

                    b.HasData(
                        new
                        {
                            Index = 0,
                            Count = 0
                        },
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        },
                        new
                        {
                            Index = 7,
                            Count = 0
                        },
                        new
                        {
                            Index = 8,
                            Count = 0
                        },
                        new
                        {
                            Index = 9,
                            Count = 0
                        },
                        new
                        {
                            Index = 10,
                            Count = 0
                        },
                        new
                        {
                            Index = 11,
                            Count = 0
                        },
                        new
                        {
                            Index = 12,
                            Count = 0
                        },
                        new
                        {
                            Index = 13,
                            Count = 0
                        },
                        new
                        {
                            Index = 14,
                            Count = 0
                        },
                        new
                        {
                            Index = 15,
                            Count = 0
                        },
                        new
                        {
                            Index = 16,
                            Count = 0
                        },
                        new
                        {
                            Index = 17,
                            Count = 0
                        },
                        new
                        {
                            Index = 18,
                            Count = 0
                        },
                        new
                        {
                            Index = 19,
                            Count = 0
                        },
                        new
                        {
                            Index = 20,
                            Count = 0
                        },
                        new
                        {
                            Index = 21,
                            Count = 0
                        },
                        new
                        {
                            Index = 22,
                            Count = 0
                        },
                        new
                        {
                            Index = 23,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.LocalMonth", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("LocalMonths");

                    b.HasData(
                        new
                        {
                            Index = 0,
                            Count = 0
                        },
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        },
                        new
                        {
                            Index = 7,
                            Count = 0
                        },
                        new
                        {
                            Index = 8,
                            Count = 0
                        },
                        new
                        {
                            Index = 9,
                            Count = 0
                        },
                        new
                        {
                            Index = 10,
                            Count = 0
                        },
                        new
                        {
                            Index = 11,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.LocalWeekday", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("LocalWeekdays");

                    b.HasData(
                        new
                        {
                            Index = 0,
                            Count = 0
                        },
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.Minute", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Minutes");

                    b.HasData(
                        new
                        {
                            Index = 0,
                            Count = 0
                        },
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        },
                        new
                        {
                            Index = 7,
                            Count = 0
                        },
                        new
                        {
                            Index = 8,
                            Count = 0
                        },
                        new
                        {
                            Index = 9,
                            Count = 0
                        },
                        new
                        {
                            Index = 10,
                            Count = 0
                        },
                        new
                        {
                            Index = 11,
                            Count = 0
                        },
                        new
                        {
                            Index = 12,
                            Count = 0
                        },
                        new
                        {
                            Index = 13,
                            Count = 0
                        },
                        new
                        {
                            Index = 14,
                            Count = 0
                        },
                        new
                        {
                            Index = 15,
                            Count = 0
                        },
                        new
                        {
                            Index = 16,
                            Count = 0
                        },
                        new
                        {
                            Index = 17,
                            Count = 0
                        },
                        new
                        {
                            Index = 18,
                            Count = 0
                        },
                        new
                        {
                            Index = 19,
                            Count = 0
                        },
                        new
                        {
                            Index = 20,
                            Count = 0
                        },
                        new
                        {
                            Index = 21,
                            Count = 0
                        },
                        new
                        {
                            Index = 22,
                            Count = 0
                        },
                        new
                        {
                            Index = 23,
                            Count = 0
                        },
                        new
                        {
                            Index = 24,
                            Count = 0
                        },
                        new
                        {
                            Index = 25,
                            Count = 0
                        },
                        new
                        {
                            Index = 26,
                            Count = 0
                        },
                        new
                        {
                            Index = 27,
                            Count = 0
                        },
                        new
                        {
                            Index = 28,
                            Count = 0
                        },
                        new
                        {
                            Index = 29,
                            Count = 0
                        },
                        new
                        {
                            Index = 30,
                            Count = 0
                        },
                        new
                        {
                            Index = 31,
                            Count = 0
                        },
                        new
                        {
                            Index = 32,
                            Count = 0
                        },
                        new
                        {
                            Index = 33,
                            Count = 0
                        },
                        new
                        {
                            Index = 34,
                            Count = 0
                        },
                        new
                        {
                            Index = 35,
                            Count = 0
                        },
                        new
                        {
                            Index = 36,
                            Count = 0
                        },
                        new
                        {
                            Index = 37,
                            Count = 0
                        },
                        new
                        {
                            Index = 38,
                            Count = 0
                        },
                        new
                        {
                            Index = 39,
                            Count = 0
                        },
                        new
                        {
                            Index = 40,
                            Count = 0
                        },
                        new
                        {
                            Index = 41,
                            Count = 0
                        },
                        new
                        {
                            Index = 42,
                            Count = 0
                        },
                        new
                        {
                            Index = 43,
                            Count = 0
                        },
                        new
                        {
                            Index = 44,
                            Count = 0
                        },
                        new
                        {
                            Index = 45,
                            Count = 0
                        },
                        new
                        {
                            Index = 46,
                            Count = 0
                        },
                        new
                        {
                            Index = 47,
                            Count = 0
                        },
                        new
                        {
                            Index = 48,
                            Count = 0
                        },
                        new
                        {
                            Index = 49,
                            Count = 0
                        },
                        new
                        {
                            Index = 50,
                            Count = 0
                        },
                        new
                        {
                            Index = 51,
                            Count = 0
                        },
                        new
                        {
                            Index = 52,
                            Count = 0
                        },
                        new
                        {
                            Index = 53,
                            Count = 0
                        },
                        new
                        {
                            Index = 54,
                            Count = 0
                        },
                        new
                        {
                            Index = 55,
                            Count = 0
                        },
                        new
                        {
                            Index = 56,
                            Count = 0
                        },
                        new
                        {
                            Index = 57,
                            Count = 0
                        },
                        new
                        {
                            Index = 58,
                            Count = 0
                        },
                        new
                        {
                            Index = 59,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.Month", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Months");

                    b.HasData(
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        },
                        new
                        {
                            Index = 7,
                            Count = 0
                        },
                        new
                        {
                            Index = 8,
                            Count = 0
                        },
                        new
                        {
                            Index = 9,
                            Count = 0
                        },
                        new
                        {
                            Index = 10,
                            Count = 0
                        },
                        new
                        {
                            Index = 11,
                            Count = 0
                        },
                        new
                        {
                            Index = 12,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.Second", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Seconds");

                    b.HasData(
                        new
                        {
                            Index = 0,
                            Count = 0
                        },
                        new
                        {
                            Index = 1,
                            Count = 0
                        },
                        new
                        {
                            Index = 2,
                            Count = 0
                        },
                        new
                        {
                            Index = 3,
                            Count = 0
                        },
                        new
                        {
                            Index = 4,
                            Count = 0
                        },
                        new
                        {
                            Index = 5,
                            Count = 0
                        },
                        new
                        {
                            Index = 6,
                            Count = 0
                        },
                        new
                        {
                            Index = 7,
                            Count = 0
                        },
                        new
                        {
                            Index = 8,
                            Count = 0
                        },
                        new
                        {
                            Index = 9,
                            Count = 0
                        },
                        new
                        {
                            Index = 10,
                            Count = 0
                        },
                        new
                        {
                            Index = 11,
                            Count = 0
                        },
                        new
                        {
                            Index = 12,
                            Count = 0
                        },
                        new
                        {
                            Index = 13,
                            Count = 0
                        },
                        new
                        {
                            Index = 14,
                            Count = 0
                        },
                        new
                        {
                            Index = 15,
                            Count = 0
                        },
                        new
                        {
                            Index = 16,
                            Count = 0
                        },
                        new
                        {
                            Index = 17,
                            Count = 0
                        },
                        new
                        {
                            Index = 18,
                            Count = 0
                        },
                        new
                        {
                            Index = 19,
                            Count = 0
                        },
                        new
                        {
                            Index = 20,
                            Count = 0
                        },
                        new
                        {
                            Index = 21,
                            Count = 0
                        },
                        new
                        {
                            Index = 22,
                            Count = 0
                        },
                        new
                        {
                            Index = 23,
                            Count = 0
                        },
                        new
                        {
                            Index = 24,
                            Count = 0
                        },
                        new
                        {
                            Index = 25,
                            Count = 0
                        },
                        new
                        {
                            Index = 26,
                            Count = 0
                        },
                        new
                        {
                            Index = 27,
                            Count = 0
                        },
                        new
                        {
                            Index = 28,
                            Count = 0
                        },
                        new
                        {
                            Index = 29,
                            Count = 0
                        },
                        new
                        {
                            Index = 30,
                            Count = 0
                        },
                        new
                        {
                            Index = 31,
                            Count = 0
                        },
                        new
                        {
                            Index = 32,
                            Count = 0
                        },
                        new
                        {
                            Index = 33,
                            Count = 0
                        },
                        new
                        {
                            Index = 34,
                            Count = 0
                        },
                        new
                        {
                            Index = 35,
                            Count = 0
                        },
                        new
                        {
                            Index = 36,
                            Count = 0
                        },
                        new
                        {
                            Index = 37,
                            Count = 0
                        },
                        new
                        {
                            Index = 38,
                            Count = 0
                        },
                        new
                        {
                            Index = 39,
                            Count = 0
                        },
                        new
                        {
                            Index = 40,
                            Count = 0
                        },
                        new
                        {
                            Index = 41,
                            Count = 0
                        },
                        new
                        {
                            Index = 42,
                            Count = 0
                        },
                        new
                        {
                            Index = 43,
                            Count = 0
                        },
                        new
                        {
                            Index = 44,
                            Count = 0
                        },
                        new
                        {
                            Index = 45,
                            Count = 0
                        },
                        new
                        {
                            Index = 46,
                            Count = 0
                        },
                        new
                        {
                            Index = 47,
                            Count = 0
                        },
                        new
                        {
                            Index = 48,
                            Count = 0
                        },
                        new
                        {
                            Index = 49,
                            Count = 0
                        },
                        new
                        {
                            Index = 50,
                            Count = 0
                        },
                        new
                        {
                            Index = 51,
                            Count = 0
                        },
                        new
                        {
                            Index = 52,
                            Count = 0
                        },
                        new
                        {
                            Index = 53,
                            Count = 0
                        },
                        new
                        {
                            Index = 54,
                            Count = 0
                        },
                        new
                        {
                            Index = 55,
                            Count = 0
                        },
                        new
                        {
                            Index = 56,
                            Count = 0
                        },
                        new
                        {
                            Index = 57,
                            Count = 0
                        },
                        new
                        {
                            Index = 58,
                            Count = 0
                        },
                        new
                        {
                            Index = 59,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.TotalClicks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TotalClicks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 0
                        });
                });

            modelBuilder.Entity("ButtonStatistics.Models.Year", b =>
                {
                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("Index");

                    b.ToTable("Years");

                    b.HasData(
                        new
                        {
                            Index = 2015,
                            Count = 0
                        },
                        new
                        {
                            Index = 2016,
                            Count = 0
                        },
                        new
                        {
                            Index = 2017,
                            Count = 0
                        },
                        new
                        {
                            Index = 2018,
                            Count = 0
                        },
                        new
                        {
                            Index = 2019,
                            Count = 0
                        },
                        new
                        {
                            Index = 2020,
                            Count = 0
                        },
                        new
                        {
                            Index = 2021,
                            Count = 0
                        },
                        new
                        {
                            Index = 2022,
                            Count = 0
                        },
                        new
                        {
                            Index = 2023,
                            Count = 0
                        },
                        new
                        {
                            Index = 2024,
                            Count = 0
                        },
                        new
                        {
                            Index = 2025,
                            Count = 0
                        },
                        new
                        {
                            Index = 2026,
                            Count = 0
                        },
                        new
                        {
                            Index = 2027,
                            Count = 0
                        },
                        new
                        {
                            Index = 2028,
                            Count = 0
                        },
                        new
                        {
                            Index = 2029,
                            Count = 0
                        },
                        new
                        {
                            Index = 2030,
                            Count = 0
                        },
                        new
                        {
                            Index = 2031,
                            Count = 0
                        },
                        new
                        {
                            Index = 2032,
                            Count = 0
                        },
                        new
                        {
                            Index = 2033,
                            Count = 0
                        },
                        new
                        {
                            Index = 2034,
                            Count = 0
                        },
                        new
                        {
                            Index = 2035,
                            Count = 0
                        },
                        new
                        {
                            Index = 2036,
                            Count = 0
                        },
                        new
                        {
                            Index = 2037,
                            Count = 0
                        },
                        new
                        {
                            Index = 2038,
                            Count = 0
                        },
                        new
                        {
                            Index = 2039,
                            Count = 0
                        },
                        new
                        {
                            Index = 2040,
                            Count = 0
                        },
                        new
                        {
                            Index = 2041,
                            Count = 0
                        },
                        new
                        {
                            Index = 2042,
                            Count = 0
                        },
                        new
                        {
                            Index = 2043,
                            Count = 0
                        },
                        new
                        {
                            Index = 2044,
                            Count = 0
                        },
                        new
                        {
                            Index = 2045,
                            Count = 0
                        },
                        new
                        {
                            Index = 2046,
                            Count = 0
                        },
                        new
                        {
                            Index = 2047,
                            Count = 0
                        },
                        new
                        {
                            Index = 2048,
                            Count = 0
                        },
                        new
                        {
                            Index = 2049,
                            Count = 0
                        },
                        new
                        {
                            Index = 2050,
                            Count = 0
                        },
                        new
                        {
                            Index = 2051,
                            Count = 0
                        },
                        new
                        {
                            Index = 2052,
                            Count = 0
                        },
                        new
                        {
                            Index = 2053,
                            Count = 0
                        },
                        new
                        {
                            Index = 2054,
                            Count = 0
                        },
                        new
                        {
                            Index = 2055,
                            Count = 0
                        },
                        new
                        {
                            Index = 2056,
                            Count = 0
                        },
                        new
                        {
                            Index = 2057,
                            Count = 0
                        },
                        new
                        {
                            Index = 2058,
                            Count = 0
                        },
                        new
                        {
                            Index = 2059,
                            Count = 0
                        },
                        new
                        {
                            Index = 2060,
                            Count = 0
                        },
                        new
                        {
                            Index = 2061,
                            Count = 0
                        },
                        new
                        {
                            Index = 2062,
                            Count = 0
                        },
                        new
                        {
                            Index = 2063,
                            Count = 0
                        },
                        new
                        {
                            Index = 2064,
                            Count = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
